### ISSUE TITLE
Unable to build in XCode

### ISSUE THREAD

**Issue by brbrr** [COx2/juce_meets_DaisySP#1]
Hi. Thank you for the example! 

Unfortunately, I can not make it work in my XCode. 

When trying to compile right away, I'm getting bunch of `Unknown type name 'constexpr'` errors. 

After I switched "C++ Lanuage Dialect" to `C++11` I see the following error: `Constexpr function never produces a constant expression`

Any idea what I'm doing wrong?

**Comment by COx2** [comment]
Thanks for your interest.
This is my guess, if the PR that is being worked on by the original DaisySP repository is merged, it may solve the problem of  C++11 compatibility.
Refer: https://github.com/electro-smith/DaisySP/pull/159

As soon as the PR on above is merged, I will update this repository as well.

**Comment by brbrr** [comment]
Thanks! I was able to resolve the problem by adding `set(CMAKE_CXX_STANDARD 17)` into a CMake config file.

**Comment by stephenhensley** [comment]
Just merged electro-smith/DaisySP#159 . So should be good to go even with c++ 2011 and earlier.

**Comment by COx2** [comment]
@stephenhensley 
Thanks!! Good stuff!!
